[package]
name = "getline"
version = "0.1.0"
authors = ["Thomas Martin <thomas@oopss.org>"]
edition = "2018"
description = "Extract given line numbers from text stream"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
